# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-15 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PBSMMLightAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('link_to_api_record', models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='API Endpoint')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('date_last_api_update', models.DateTimeField(help_text=b'Not set by API', null=True, verbose_name='Last API Retrieval')),
                ('ingest_on_save', models.BooleanField(default=False, help_text=b'If true, then will update values from the PBSMM API on save()', verbose_name='Ingest on Save')),
                ('last_api_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='Last API Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('link_to_api_record', models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='API Endpoint')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('date_last_api_update', models.DateTimeField(help_text=b'Not set by API', null=True, verbose_name='Last API Retrieval')),
                ('ingest_on_save', models.BooleanField(default=False, help_text=b'If true, then will update values from the PBSMM API on save()', verbose_name='Ingest on Save')),
                ('last_api_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='Last API Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('link_to_api_record', models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='API Endpoint')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('date_last_api_update', models.DateTimeField(help_text=b'Not set by API', null=True, verbose_name='Last API Retrieval')),
                ('ingest_on_save', models.BooleanField(default=False, help_text=b'If true, then will update values from the PBSMM API on save()', verbose_name='Ingest on Save')),
                ('last_api_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='Last API Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightFranchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('link_to_api_record', models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='API Endpoint')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('date_last_api_update', models.DateTimeField(help_text=b'Not set by API', null=True, verbose_name='Last API Retrieval')),
                ('ingest_on_save', models.BooleanField(default=False, help_text=b'If true, then will update values from the PBSMM API on save()', verbose_name='Ingest on Save')),
                ('last_api_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='Last API Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightRemoteAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('link_to_api_record', models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='API Endpoint')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('date_last_api_update', models.DateTimeField(help_text=b'Not set by API', null=True, verbose_name='Last API Retrieval')),
                ('ingest_on_save', models.BooleanField(default=False, help_text=b'If true, then will update values from the PBSMM API on save()', verbose_name='Ingest on Save')),
                ('last_api_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='Last API Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('link_to_api_record', models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='API Endpoint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('link_to_api_record', models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='API Endpoint')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('date_last_api_update', models.DateTimeField(help_text=b'Not set by API', null=True, verbose_name='Last API Retrieval')),
                ('ingest_on_save', models.BooleanField(default=False, help_text=b'If true, then will update values from the PBSMM API on save()', verbose_name='Ingest on Save')),
                ('last_api_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='Last API Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBSMMLightSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text=b'Not set by API', verbose_name='Created On')),
                ('object_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('publish_status', models.PositiveIntegerField(choices=[(0, b'NOT AVAIL.'), (1, b'AVAILABLE')], default=0, verbose_name='Publish Status')),
                ('link_to_api_record', models.URLField(blank=True, help_text=b'Endpoint to original record from the API', null=True, verbose_name='API Endpoint')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('date_last_api_update', models.DateTimeField(help_text=b'Not set by API', null=True, verbose_name='Last API Retrieval')),
                ('ingest_on_save', models.BooleanField(default=False, help_text=b'If true, then will update values from the PBSMM API on save()', verbose_name='Ingest on Save')),
                ('last_api_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='Last API Status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
