# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmmlightseason',
            name='date_last_api_update',
            field=models.DateTimeField(help_text=b'Not set by API', null=True, verbose_name='Last API Retrieval'),
        ),
        migrations.AddField(
            model_name='pbsmmlightseason',
            name='ingest_on_save',
            field=models.BooleanField(default=False, help_text=b'If true, then will update values from the PBSMM API on save()', verbose_name='Ingest on Save'),
        ),
        migrations.AddField(
            model_name='pbsmmlightseason',
            name='last_api_status',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Last API Status'),
        ),
    ]
